#define MICROPY_HW_BOARD_NAME               "Walnut Pi Pico W"
#define MICROPY_HW_MCU_NAME                 "ESP32-S3"
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "WPI_PICO_W"

#define MICROPY_PY_MACHINE_DAC              (0)

#define MICROPY_HW_I2C0_SCL                 (9)
#define MICROPY_HW_I2C0_SDA                 (8)

#define MICROPY_ENABLE_TFTLCD				(1)
#define MICROPY_HW_ESPAI				(1)
#define MICROPY_ENABLE_FACE_DETECTION	(1)
// #define MICROPY_ENABLE_CAT_DETECTION	(1)
// #define MICROPY_ENABLE_COLOR_DETECTION	(1)
// #define MICROPY_ENABLE_CODE_RECOGNITION	(1)
// #define MICROPY_ENABLE_MOTION_DETECTION	(1)
// #define MICROPY_ENABLE_FACE_RECOGNITION (1)


